package uniflow.view;

import uniflow.model.Usuario_dao;
import uniflow.model.Usuario;
import uniflow.model.Estudiante_dao;
import uniflow.model.Estudiante;
import javax.swing.JOptionPane;
import uniflow.controller.RegistroControllerr;

/**
 *
 * @author user
 */
public class Ventana_regitrar extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana_regitrar.class.getName());

    /**
     * Creates new form Regitrar
     */
    public Ventana_regitrar() {
        initComponents();
          setLocationRelativeTo(null);
        // Agrega esto aquí y se cargará APENAS abras la ventana
        cbxROL.removeAllItems();
        cbxROL.addItem("Seleccione un Rol...");
        cbxROL.addItem("ESTUDIANTE");
        cbxROL.addItem("DOCENTE");
        /////////////////////////////////////
        cbxCARRERA.setVisible(false);
txtcarrera.setVisible(false);

        ///
    cbxCARRERA.removeAllItems();
        cbxCARRERA.addItem("Seleccione...");
        cbxCARRERA.addItem("Ingeniería de Sistemas");
        cbxCARRERA.addItem("Ingeniería Mecatrónica");
        cbxCARRERA.addItem("Ingeniería Industrial");
        cbxCARRERA.addItem("Ingeniería Civil");
        cbxCARRERA.addItem("Ingeniería Electrónica");
        cbxCARRERA.addItem("Ingeniería Ambiental");
        cbxCARRERA.addItem("Administración de Empresas");
        cbxCARRERA.addItem("Contaduría Pública");
        ////
       txtcarrera.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ROL = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCORREO = new javax.swing.JTextField();
        txtNOMBRE = new javax.swing.JTextField();
        txtCONTRASEÑA = new javax.swing.JPasswordField();
        cbxROL = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnatras = new javax.swing.JButton();
        cbxCARRERA = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtcarrera = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Correo");

        ROL.setText("Rol");

        jLabel4.setText("Contraseña");

        cbxROL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxROL.addActionListener(this::cbxROLActionPerformed);

        btnRegistrar.setText("Resgitrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnatras.setText("Atras");
        btnatras.addActionListener(this::btnatrasActionPerformed);

        cbxCARRERA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCARRERA.addActionListener(this::cbxCARRERAActionPerformed);

        txtcarrera.setText("Carrera del estudiante");
        txtcarrera.addActionListener(this::txtcarreraActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(ROL)))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxROL, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCONTRASEÑA, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCORREO, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRegistrar)
                                .addGap(89, 89, 89)
                                .addComponent(btnatras))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxCARRERA, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCORREO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCONTRASEÑA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ROL)
                    .addComponent(cbxROL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCARRERA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtcarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnatras))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxROLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxROLActionPerformed
 

     Object item = cbxROL.getSelectedItem();

    if (item == null) {
        return;
    }

    String rol = item.toString();

    if (rol.equalsIgnoreCase("Estudiante")) {
        cbxCARRERA.setVisible(true);
        txtcarrera.setVisible(true);
     
    } else {
        cbxCARRERA.setVisible(false);
        txtcarrera.setVisible(false);
    
    
}
    

    }//GEN-LAST:event_cbxROLActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        // 1. Obtener datos (Usamos String.valueOf para el JPasswordField)
        String nombre = txtNOMBRE.getText().trim();
        String correo = txtCORREO.getText().trim();
        String password = String.valueOf(txtCONTRASEÑA.getPassword());

        // 2. Validar que el ComboBox no esté en la opción por defecto ("Seleccione...")
        if (cbxROL.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "⚠️ Por favor, seleccione un Rol");
            return;

        }

        String rol = cbxROL.getSelectedItem().toString();

        // 3. Validación básica de campos vacíos para evitar basura en la DB
        if (nombre.isEmpty() || correo.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Todos los campos son obligatorios");
            return;
        }

        String carrera = "";

    if (rol.equalsIgnoreCase("Estudiante")) {

        if (cbxCARRERA.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "⚠️ Seleccione carrera");
            return;
        }

        carrera = cbxCARRERA.getSelectedItem().toString();
    }

    // 🔥 AQUÍ USAS EL CONTROLLER
    RegistroControllerr controller = new RegistroControllerr();
    boolean res = controller.registrarUsuario(nombre, correo, password, rol, carrera);

    if (res) {
        JOptionPane.showMessageDialog(this, "✅ Usuario registrado");

        txtNOMBRE.setText("");
        txtCORREO.setText("");
        txtCONTRASEÑA.setText("");
        cbxROL.setSelectedIndex(0);
        cbxCARRERA.setSelectedIndex(0);

    } else {
        JOptionPane.showMessageDialog(this, "❌ Error al registrar");
    }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
        // TODO add your handling code here:
        Ventana_usuario Usuario = new Ventana_usuario();
        Usuario.setVisible(true);
        
    }//GEN-LAST:event_btnatrasActionPerformed

    private void cbxCARRERAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCARRERAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCARRERAActionPerformed

    private void txtcarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcarreraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventana_regitrar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ROL;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnatras;
    private javax.swing.JComboBox<String> cbxCARRERA;
    private javax.swing.JComboBox<String> cbxROL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtCONTRASEÑA;
    private javax.swing.JTextField txtCORREO;
    private javax.swing.JTextField txtNOMBRE;
    private javax.swing.JTextField txtcarrera;
    // End of variables declaration//GEN-END:variables
}
